language: php

dist: focal

php:
    - "8.2"
    - "8.3"
    - "8.4"

before_script:
    - composer install --no-interaction

script:
    - make test
    - make check-style

after_success:
    - bash <(curl -s https://codecov.io/bash)
