language: php

dist: xenial

php:
    - "7.4"
    - "8.0"

before_script:
    - composer install --no-interaction

script:
    - make test
    - make check-style

after_success:
    - bash <(curl -s https://codecov.io/bash)
