<?php

namespace Dash;

/**
 * Keys elements by the common values generated by an iteratee.
 *
 * @category Iterable
 * @param iterable $iterable
 * @param callable $iteratee (optional) Invoked with ($element) for each element of $iterable
 * @return array map of key => grouped elements
 *
 * @example
	keyBy([
		['name' => 'John', 'gender' => 'male'],
		['name' => 'Alice', 'gender' => 'female'],
		['name' => 'Jane', 'gender' => 'female'],
		['name' => 'Peter', 'gender' => 'male'],
		['name' => 'Fred', 'gender' => 'male'],
	], 'name');
	// === [
		'John'  => ['name' => 'John', 'gender' => 'male'],
		'Alice' => ['name' => 'Alice', 'gender' => 'female'],
		'Jane'  => ['name' => 'Jane', 'gender' => 'female'],
		'Peter' => ['name' => 'Peter', 'gender' => 'male'],
		'Fred'  => ['name' => 'Fred', 'gender' => 'male'],
	]
 */
function keyBy($iterable, $iteratee = 'Dash\identity')
{
	assertType($iterable, ['iterable']);

	return reduce($iterable, function ($grouped, $value) use ($iteratee) {
		$key = get($value, $iteratee);
		$grouped[$key] = $value;
		return $grouped;
	});
}
